# Site settings
title: Ma Jun OS
description: 'Business Card Page'
url: 'https://www.xiaopeng.com/'
baseurl: ''
profilepic: '/images/majun.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Ma Jun'
  email: 17665000622@163.com
# twitter_username: thomzuehlke
# facebook_username: joshgerdes
  github_username:  majunos
#  linkedin_username:  thomas-zühlke-889182165
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
